STATUS_PENDING = 0
STATUS_CONFIRMED = 1
STATUS_REJECTED = 2

STATUSES = (
    (STATUS_PENDING, 'Pending'),
    (STATUS_CONFIRMED, 'Confirmed'),
    (STATUS_REJECTED, 'Rejected'),
)


REQUEST_SICKNESS = 1
REQUEST_VACATION = 2
REQUEST_DAYOFF = 3
REQUEST_TYPES = (
    (REQUEST_SICKNESS, 'sickness'),
    (REQUEST_VACATION, 'vacation'),
    (REQUEST_DAYOFF, 'day off'),
)