# Generated by Django 2.1.4 on 2019-01-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190106_1414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_us',
            new_name='ContactUs',
        ),
    ]
