# Generated by Django 2.1.4 on 2019-01-10 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190106_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDayOffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('confirmed', models.NullBooleanField(choices=[(None, ''), (True, 'Confirmed'), (False, 'Rejected')], default=None, max_length=3)),
                ('reason', models.CharField(choices=[('V', 'Vacation'), ('D', 'Disease'), ('O', 'At own expense')], max_length=1)),
                ('user', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact-us'},
        ),
    ]
