# Generated by Django 2.1.4 on 2019-01-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190110_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdayoffs',
            name='reason',
            field=models.CharField(choices=[('V', 'Vacation'), ('D', 'Disease'), ('A', 'At own expense')], max_length=1),
        ),
    ]
