# Generated by Django 2.1.4 on 2019-01-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190110_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdayoffs',
            name='reason',
            field=models.CharField(choices=[('Vacation', 'Vacation'), ('Disease', 'Disease'), ('At own expense', 'At own expense')], max_length=20),
        ),
    ]
