# Generated by Django 2.1.4 on 2019-01-13 13:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190110_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestdayoffs',
            options={'verbose_name_plural': 'Request day offs'},
        ),
        migrations.RemoveField(
            model_name='requestdayoffs',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='requestdayoffs',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='requestdayoffs',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Rejected')], default=0),
        ),
        migrations.AddField(
            model_name='requestdayoffs',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'sickness'), (2, 'vacation'), (3, 'day off')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='sickness_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='vacations_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestdayoffs',
            name='from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='requestdayoffs',
            name='reason',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='requestdayoffs',
            name='to_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='requestdayoffs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayoffs', to=settings.AUTH_USER_MODEL),
        ),
    ]
