# Generated by Django 2.1.4 on 2019-01-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190113_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdayoffs',
            name='reason',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
