# Generated by Django 2.1.4 on 2019-01-24 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20190124_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdayoffs',
            name='status_changed',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
